options:
  #暂时弃用
  auto-update: false

waila:

  # 如果设置为true，将禁用所有玩家的waila,
  # 凌驾于个人偏好之上 'disabled-in'
  disabled: false

  # 禁用WAILA的世界列表
  disabled-in: []

  # 用 'bossbar' 还是 'hotbar'
  location: bossbar

  #是否保留文本的颜色和格式。如果设置为false，那么默认是白色。
  use-original-colors: true

  #  bossbar 的颜色。必须是'snake_case'中的有效颜色。
  # 'inherit 的意思是'将boss栏的颜色匹配到文本的颜色'。
  # 'default 是白色的
  bossbar-color: inherit

  # 展示货运网络上有多少个节点;在连接器和管理器中显示
  show-cargo-size: true

  # 显示输出和输入节点
  show-cargo-channel: true

  # 显示能源网络上有多少个节点;在连接器和调节器上显示
  show-energy-size: true

  # 显示电容
  show-energy-stored: true

  # 显示大多数机器
  show-machine-progress: true

  # 显示大多数发电机
  show-generator-generation: true

  # 多少tick更新一次准星方块信息, 越高占用越低, 越低体验越好性能越差, 20tick=1秒
  tick-rate: 10