name: SlimeHUDPlus

author: SchnTgaiSpock,鬼斩,AlanZhao

description: 一个实用插件，添加了一个可切换的WAILA(我在看什么)HUD放置Slimefun项目。本项目是原版的增强分支.

main: io.github.schntgaispock.slimehud.SlimeHUD

website: https://github.com/mxlt02/SlimeHUDPlus

version: ${project.version}

api-version: 1.14

depend:
- Slimefun
- GuizhanLibPlugin

commands:
  slimehud:
    description: /slimehud
    aliases: [sfhud, sfh]
    usage: 按[tab]查看使用提示
    permission: slimehud.togglewaila
    permission-message: 您没有权限切换您的准星粘液物品显示!

permissions:
  slimehud.togglewaila:
    description: 切换准星显示
    default: op
  slimehud.admin.togglewaila:
    description: 切换别人的准星显示
    default: op