name: SlimeHUD

author: SchnTgaiSpock

description: A utility addon that adds a toggleable WAILA (What Am I Looking At) HUD for placed Slimefun items.

main: io.github.schntgaispock.slimehud.SlimeHUD

website: https://github.com/SchnTgaiSpock/SlimeHUD

version: ${project.version}

api-version: 1.14

depend:
- Slimefun
- GuizhanLibPlugin

commands:
  slimehud:
    description: /slimehud
    aliases: [sfhud, sfh]
    usage: Press [tab] for usage hints
    permission: slimehud.togglewaila
    permission-message: 您没有权限切换您的准星粘液物品显示!

permissions:
  slimehud.togglewaila:
    description: 切换准星显示
    default: false